### ISSUE TITLE
Error when parsing @foxpath string expression starting with an integer

### ISSUE THREAD

**Issue by dzim** [hrennau/greenfox#1]
The following expression gives an error:

<folder foxpath=".\frameworks\1xmlschema"

The variable $textAfter contains the string after the integer:

    <errors>
      <error code="SYNTAX_ERROR" msg="Unexpected text after expression end: xmlschema"/>
    </errors>

The following expression is OK:

<folder foxpath=".\frameworks\x1mlschema">

 Tested in current master branch with example-schemas\exploring-oxygen-contents\FolderContent\folder-content.oxygen.gfox.xml

**Comment by hrennau** [comment]
Grüß Dich, Daniel,
Deine Mails sehe ich erst gerade jetzt, da ich unterwegs und tatsächlich drei Tage offline war.
Zum Parsing-Fehler eine schnelle Antwort: die foxpath - Syntaxregeln besagen, dass eine Ziffer am Anfang eines Datei/Verzeichnis-Namens durch vorgestelltes ~ (tilde) escaped werden muss (wie auch Whitespace innerhalb von Namen).

Bitte so anpassen:

<folder foxpath=".\frameworks\~1xmlschema"
Ich nehme es als Anregung auf, diesen möglichen Fehler durch das Meta-Schema aufdecken zu lassen!
Später antworte ich auf die beiden anderen Mails.
Bis dahin, schöne Grüße -Hans-Jürgen

    Am Mittwoch, 4. März 2020, 11:12:01 MEZ hat Daniel Zimmel <notifications@github.com> Folgendes geschrieben:  
 
 
The following expression gives an error:

<folder foxpath=".\frameworks\1xmlschema"

The variable $textAfter contains the string after the integer:
<errors>
  <error code="SYNTAX_ERROR" msg="Unexpected text after expression end: xmlschema"/>
</errors>

The following expression is OK:

Tested in current master branch with example-schemas\exploring-oxygen-contents\FolderContent\folder-content.oxygen.gfox.xml

**Comment by hrennau** [comment]
A digit as first character of a Foxpath step (that is, folder or file name) must be escaped by a leading tilde (~).  Example: In order to list the contents of subfolder "20200101", use an expression similar to the following: 
~20200101
/a/b/~20200101
../~20200101
